name: Update CrowdSec

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync IPs to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_LIST_ID: ${{ secrets.CLOUDFLARE_LIST_ID }}
        run: |
          curl -s https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/refs/heads/main/all.txt | \
          grep -E '^[0-9]' | \
          awk '{print "{\"ip\": \"" $1 "\", \"comment\": \"crowdsec-sync\"}"}' | \
          paste -sd, - | sed 's/^/[/' | sed 's/$/]/' > crowdsec.json

          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/gateway/lists/$CLOUDFLARE_LIST_ID/items" \
               -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
               -H "Content-Type: application/json" \
               --data @crowdsec.json
